<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div id="filter-products" class="owl-carousel owl-theme filter-products">
        <?php $_collectionSize = $_productCollection->count() ?>
        <!--<div class="products small-list">-->
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <div class="item">
                    <div class="item-area">
                        <!-- Vinu changes adding wishlist at the top & also changing icon of wishlist in the box -->
                        <!--<?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxWishlist('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" class="addtowishlist-bestsellers" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-star"></i></a>
                        <?php endif; ?>-->
                        <!-- Vinu changes end -->
                        <div class="product-image-area">
                            <?php
                                if( Mage::getStoreConfig("quickview/general/enableview", $code) ){
                                    $base_url = $this->getUrl();
                                    if(strpos($base_url,'?')!==false)
                                        $base_url = explode("?",$this->getUrl());
                                    if(is_array($base_url))
                                        $base_url = $base_url[0];
                                    $base_url .= "quickview/index/view/";
                                    $quickview_url = $base_url."id/".$_product->getId();
                            ?>
                                    <a href="<?php echo $quickview_url; ?>" class="quickview-icon"><i class="icon-export"></i><span><?php echo $this->__("Quick View"); ?></span></a>
                            <?php
                                }
                            ?>
                            <!-- Vinu changes adding out of stock display over the image -->
                            <?php if(!$_product->isSaleable()): ?>
                                <a class="outofstock" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Out of stock') ?></span></a>
                            <?php endif; ?>
                            <!-- Vinu changes end -->
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <img src="<?php if(Mage::getStoreConfig("porto_settings/category/aspect_ratio",$code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(150);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(Mage::getStoreConfig("porto_settings/category/ratio_width",$code),Mage::getStoreConfig("porto_settings/category/ratio_height",$code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            </a>
                        </div>
                        <div class="details-area">
                            <h5 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h5>
                            <?php 
                                if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                            ?>
                                <?php 
                                    $review_html = $this->getReviewsSummaryHtml($_product, 'short');
                                    if($review_html){
                                        echo $review_html;
                                    }else{
                                ?>
                                <div class="ratings">
                                    <div class="rating-box">
                                        <div class="rating" style="width:0"></div>
                                    </div>
                                </div>
                            <?php                            
                                }
                            ?>
                            <?php else: ?>
                                <div class="ratings">
                                    <div class="rating-box">
                                        <div class="rating" style="width:0"></div>
                                    </div>
                                </div>
                            <?php 
                                endif;
                            ?>
                            <?php if($_product->getR4q_hide_price()): ?>
                                <span>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo "View Details" ?></a>
                                </span>
                            <?php else : ?>
                                <!-- Vinu changes for adding mrp price only if value is present for product -->
                                <?php if($_product->getMrp_price()!= ''): ?>
                                    <span class="mrp-price list-page"><?php echo Mage::helper('core')->currency($_product->getMrp_price(),true,false); ?></span>
                                    <?php 
                                        $MrpPrice = $_product->getMrp_price();
                                        $MainPrice = $_product->getPrice();
                                        $percentage = 0;
                                        if ($MrpPrice > $MainPrice) {
                                            $percentage = round(($MrpPrice - $MainPrice) * 100 / $MrpPrice);
                                        }

                                        if ($percentage) {
                                            echo $this->__('(%s', $percentage . '% off)');
                                        }    
                                    ?>
                                <?php endif; ?>
                                <!-- Vinu changes end -->
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            <?php endif; ?>
                            <!--Vinu changes end-->                              
                        </div>
                        <div class="clearer"></div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(function($){
            $("#filter-products").owlCarousel({
                navigation : true, // Show next and prev buttons
                slideSpeed : 300,
                paginationSpeed : 400,
                //singleItem:true,
                pagination:false,
                stopOnHover: true,
                rewindNav: true,
                rewindSpeed: 400,
                autoPlay: true,
                <?php if (!Mage::getStoreConfig("porto_settings/general/rtl",$code)) : ?>
                    navigationText:["<i class='icon-left-open'></i>","<i class='icon-right-open'></i>"]
                <?php else : ?>
                    navigationText:["<i class='icon-right-open'></i>","<i class='icon-left-open'></i>"]
                <?php endif; ?>
            });
        });
    </script>
<?php endif; ?>