<!-- Categories display start -->
<div class="mt-10">
	<?php 
	
	$categories = Mage::getResourceModel('catalog/category_collection')
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('is_active', 1) //only active categories
    ->addAttributeToFilter('parent_id', 2)//get only subcategories of the category with id 10
    ->addAttributeToSort('position')//sort by position
	;
	foreach ($categories as $_category): 
		$cat = Mage::getModel('catalog/category')->load($_category->getId());
		$count = $cat->getProductCount(); 
	?>	
		<div class="row footer-categories">
			<div class="levelonecats">
				<!--Vinu changes to remove link on base category text-->
				<!--<a href="<?php echo Mage::getUrl($cat->getUrlPath()); ?>" class="footer-cat text-color11" title="<?php echo $_category->getName() ?>"><?php echo $_category->getName() ?> : </a>-->
				<a class="footer-cat text-color11"><?php echo $_category->getName() ?> : </a>
				<!--Vinu changes end to remove link on base category text-->
			</div>
			<!--<?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
            <?php $_subcategories = $_category->getChildrenCategories() ?>
			<?php 
			$i=0; 
			foreach ($_subcategories as $subcategory): 
				$subcat = Mage::getModel('catalog/category')->load($subcategory->getId()); ?>
				<?php if($i==0): ?>
					<a class="inside-link-first text-color11" href="<?php echo Mage::getUrl($subcat->getUrlPath()); ?>" title="<?php echo $subcategory->getName() ?>"> <?php echo '&nbsp;'.$subcategory->getName().'&nbsp;' ?> </a>
				<?php else: ?>
				<a class="inside-link text-color11" href="<?php echo Mage::getUrl($subcat->getUrlPath()); ?>" title="<?php echo $subcategory->getName() ?>"><span>|</span><?php echo '&nbsp;'.$subcategory->getName().'&nbsp;' ?> </a>
				<?php endif; ?>		
			<?php 
			$i++;
			endforeach ?>-->
			<?php $newSubCategories = explode(',', $_category->getChildren()); ?>
            <?php $i=0; foreach ($newSubCategories as $newSubCategoryId): ?>
                <?php $newCategory = Mage::getModel('catalog/category')->load($newSubCategoryId); ?>
                <?php if($i==0): ?>
					<a class="inside-link-first text-color11" href="<?php echo $newCategory->getURL(); ?>" title="<?php echo $newCategory->getName(); ?>"> <?php echo '&nbsp;'.$newCategory->getName().'&nbsp;' ?> </a>
				<?php else: ?>
					<a class="inside-link text-color11" href="<?php echo $newCategory->getURL(); ?>" title="<?php echo $newCategory->getName(); ?>"><span>|</span><?php echo '&nbsp;'.$newCategory->getName().'&nbsp;' ?> </a>
				<?php endif; ?>
            <?php 
			$i++;
			endforeach ?>
		</div>
	<?php endforeach ?>
</div>
<!-- Categories display end -->