<!--<?php
$_helper = Mage::helper('catalog/category');
$_categories = $_helper->getStoreCategories();
//$currentCategory = Mage::registry('current_category')
$category = Mage::registry('current_category');
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($category);
$attributes = $layer->getFilterableAttributes();
$manufacturers = array();
foreach ($attributes as $attribute) {
    if ($attribute->getAttributeCode() == 'manufacturer') {
        $filterBlockName = 'catalog/layer_filter_attribute';
        $result = Mage::app()->getLayout()->createBlock($filterBlockName)->setLayer($layer)->setAttributeModel($attribute)->init();
        foreach($result->getItems() as $option) {
            $manufacturers[$option->getValue()] = $option->getLabel();
            echo $option->getLabel();
        }
    }
}
//var_dump($manufacturers);
?>-->

<?php
$category = Mage::getModel('catalog/category')->load($category->getId());
$valuesCollection = Mage::getModel('catalog/product')->getCollection()
    ->addCategoryFilter($category)
    ->addAttributeToSelect('manufacturer')
    ->addAttributeToSort('entity_id','ASC')
    ->groupByAttribute('manufacturer');

$preparedManufacturers = array();            
    foreach($valuesCollection as $value) {
        $preparedManufacturers[$value->getOptionId()] = $value->getValue();
        echo $value->getValue();
    }
?>