<?php
/*
* List Sub catgories template
*/
?>

<?php
    $object = new Mage_Catalog_Block_Navigation();
    $categoyrId = 2;
    $actualCategory = Mage::getModel('catalog/category')->load($categoyrId);
    $subCategories = explode(',', $actualCategory->getChildren()); 
    $maxCategoryCount    = $this->getCategoryCount();
?>
<div class="sub-cat-list1">
	<h3 class="filter-title l-height70">
        <span class="content">
            <strong>Top Categories</strong>
        </span>
    </h3>
    <ul class="img-list1">
    	<?php $i; foreach ($subCategories as $subCategoryId): $i++; ?>
            <?php if ($i > $maxCategoryCount): break; endif; ?>
        	<?php 
        		$category = Mage::getModel('catalog/category')->load($subCategoryId);
        		if ($category->getIsActive() ): 
        	?>
        		<li class="catItem1">
            		<?php if($category->getThumbnail()): ?>
                        <img src="<?php echo Mage::getBaseUrl('media').'catalog/category/'. $category->getThumbnail(); ?>" alt=""  />
                        <span class="text-content1">
                            <span>
                                <div>
                                    <h5 class="category-name parent-category1"><a href="<?php echo $category->getURL(); ?>" title="<?php echo $category->getName(); ?>"><?php echo $category->getName(); ?></a></h5>
                                    <?php // show subs ?>
                                    <?php $newSubCategories = explode(',', $category->getChildren()); ?>
                                    <?php $j=0; foreach ($newSubCategories as $newSubCategoryId): ?>
                                        <?php $newCategory = Mage::getModel('catalog/category')->load($newSubCategoryId); ?>
                                        <div class="subCat1">
                                            <a href="<?php echo $newCategory->getURL(); ?>" title="<?php echo $newCategory->getName(); ?>"><?php echo $newCategory->getName(); ?></a>
                                        </div>
                                    <?php 
                                        $j++; 
                                        if($j==4) break;
                                        endforeach; 
                                    ?> 
                                </div>
                            </span>
                        </span>
            		<?php endif; ?> 
        		</li>
        	<?php endif; ?>
    	<?php endforeach; ?> 
    </ul>
</div>